### ISSUE TITLE
Retour

### ISSUE THREAD

**Issue by devalade** [charbossly/figma-to-code-ed2-week1#1]
[Retour]
- Il faut utiliser du PascalCase pour le nom de tes composants
- Il faut déplacer ta variable Links à l'extérieur du composant : Recommandation
- Je sais toujours pas pourquoi tu as passé le setState dans le onClick
- Évite d'envoyer le setState directement dans un composant. Tu peux créer des fonctions que tu passes

**Comment by charbossly** [comment]
Thanks for feedback... Will take it an account

**Comment by charbossly** [comment]
Composant Recommandation?

**Comment by devalade** [comment]
Tu peux créer un fichier qui va contenir tes constantes.

**Comment by charbossly** [comment]
Done
